# Generated by Django 4.2.20 on 2025-05-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=32)),
                ('industry', models.CharField(max_length=32)),
            ],
        ),
    ]
